name: Miri

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ppmd7withoutMarker:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Install rust version
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: miri, rust-std
      - name: Miri
        run: cargo +nightly miri test --features unstable-tagged-offsets --lib encoder_7::test::ppmd7encoder_without_end_marker

  ppmd7withMarker:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Install rust version
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: miri, rust-std
      - name: Miri
        run: cargo +nightly miri test --features unstable-tagged-offsets --lib encoder_7::test::ppmd7encoder_with_end_marker

  ppmd8withoutMarker:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Install rust version
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: miri, rust-std
      - name: Miri
        run: cargo +nightly miri test --features unstable-tagged-offsets --lib encoder_8::test::ppmd8encoder_without_end_marker

  ppmd8withMarker:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Install rust version
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: miri, rust-std
      - name: Miri
        run: cargo +nightly miri test --features unstable-tagged-offsets --lib encoder_8::test::ppmd8encoder_with_end_marker
